const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Behaviors.Bullet,
		C3.Behaviors.Platform,
		C3.Behaviors.Physics,
		C3.Behaviors.bound,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.solid,
		C3.Behaviors.Pin,
		C3.Behaviors.destroy,
		C3.Plugins.Keyboard,
		C3.Plugins.Text,
		C3.Plugins.Button,
		C3.Behaviors.Persist,
		C3.Plugins.LocalStorage,
		C3.Behaviors.Timer,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Platform.Acts.SetDoubleJumpEnabled,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Behaviors.Platform.Acts.SetGravity,
		C3.Behaviors.Physics.Acts.SetDensity,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Physics.Acts.Teleport,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Button.Acts.SetVisible,
		C3.Plugins.Button.Acts.SetEnabled,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.Sprite.Cnds.OnDestroyed
	];
};
self.C3_JsPropNameTable = [
	{TiledBackground: 0},
	{Bullet: 0},
	{Cloud: 0},
	{Platform: 0},
	{Physics: 0},
	{BoundToLayout: 0},
	{DragDrop: 0},
	{Bird: 0},
	{Solid: 0},
	{Sprite2: 0},
	{Ground: 0},
	{Pin: 0},
	{DestroyOutsideLayout: 0},
	{PipeDown: 0},
	{pipeUpsidedown: 0},
	{Keyboard: 0},
	{GameOver: 0},
	{RestartButton: 0},
	{Score: 0},
	{Persist: 0},
	{HighScore: 0},
	{LocalStorage: 0},
	{Timer: 0},
	{Sprite: 0},
	{SCORE: 0}
];

self.InstanceType = {
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Cloud: class extends self.ISpriteInstance {},
	Bird: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Ground: class extends self.ISpriteInstance {},
	PipeDown: class extends self.ISpriteInstance {},
	pipeUpsidedown: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	GameOver: class extends self.ITextInstance {},
	RestartButton: class extends self.IButtonInstance {},
	Score: class extends self.ITextInstance {},
	HighScore: class extends self.ITextInstance {},
	LocalStorage: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {}
}